# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SolarSystem' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'SkeletonView'

  # Pods for SolarSystem
pod 'Firebase/Core'
pod ‘Firebase/Database’
  target 'SolarSystemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SolarSystemUITests' do
    # Pods for testing
  end

end
